### ISSUE TITLE
[BUG] sample_stage1 being unable to run with certain step counts

### ISSUE THREAD

**Issue by MingkunYu** [3DTopia/3DTopia#7]
When I try to run sample_stage1.py with modified step count, it throws me an error.

Command: python -u sample_stage1.py --text "a robot" --samples 1 --sampler ddim --steps 300 --cfg_scale 7.5

Program Output:

['a robot']
LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.54 M params.
Using timesteps of 1000
/root/autodl-tmp/cache/3dtopia/lib/python3.8/site-packages/timm/models/layers/__init__.py:49: DeprecationWarning: Importing from timm.models.layers is deprecated, please import via timm.layers
  warnings.warn(f"Importing from {__name__} is deprecated, please import via timm.layers", DeprecationWarning)
Traceback (most recent call last):
  File "sample_stage1.py", line 299, in <module>
    main()
  File "sample_stage1.py", line 174, in main
    sample, _ = sampler.sample(
  File "/root/autodl-tmp/cache/3dtopia/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "/root/autodl-tmp/3dt/3d-texture/3daigc/3DTopia/ldm/models/diffusion/ddim.py", line 90, in sample
    self.make_schedule(ddim_num_steps=S, ddim_eta=eta, verbose=verbose)
  File "/root/autodl-tmp/3dt/3d-texture/3daigc/3DTopia/ldm/models/diffusion/ddim.py", line 44, in make_schedule
    ddim_sigmas, ddim_alphas, ddim_alphas_prev = make_ddim_sampling_parameters(alphacums=alphas_cumprod.cpu(),
  File "/root/autodl-tmp/3dt/3d-texture/3daigc/3DTopia/ldm/modules/diffusionmodules/util.py", line 103, in make_ddim_sampling_parameters
    alphas = alphacums[ddim_timesteps]
IndexError: index 1000 is out of bounds for dimension 0 with size 1000

So far on whole hundreds I've tested, only 200 and 400 works. Other step counts such as 300,600,800,1000 all produce the above error. What might be the cause of this? How should I solve it? Thanks!

**Comment by vinodrajendran001** [comment]
@MingkunYu  Did you manage to find a solution for this?

**Comment by MingkunYu** [comment]
> @MingkunYu Did you manage to find a solution for this?

nope, i never got it working and thus abandoned this model.
